# Created by Jekyll Writer
title: 冬木觉的小站
author: Bryan_lzh
description: 欢迎来到冬木觉
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/:num/'
twitter_username: 
github_username: BryanSer
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /WinterTreeAwake
