# Created by Jekyll Writer
title: 欢迎来到冬木觉
author: Bryan_lzh
description: 冬木觉的小站
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: jekyllwriter
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /WinterTreeAwake
